// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIOjUzV_wFp48zqesDq4oLTMEY3uSGhSw',
    appId: '1:784311936959:web:b4ded3779867188a95e30a',
    messagingSenderId: '784311936959',
    projectId: 'gayau-e5a6f',
    authDomain: 'gayau-e5a6f.firebaseapp.com',
    storageBucket: 'gayau-e5a6f.firebasestorage.app',
    measurementId: 'G-Z3GCBLZ3LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEYJ_VWRl2pB5ujEY-okc4-pTfLSXnZGc',
    appId: '1:784311936959:android:7e677c6be54ef4cb95e30a',
    messagingSenderId: '784311936959',
    projectId: 'gayau-e5a6f',
    storageBucket: 'gayau-e5a6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb8Ce5UUKZIsWYUxiCLiErZbLkNg0PzPw',
    appId: '1:784311936959:ios:e1d35ba7e3b3829295e30a',
    messagingSenderId: '784311936959',
    projectId: 'gayau-e5a6f',
    storageBucket: 'gayau-e5a6f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb8Ce5UUKZIsWYUxiCLiErZbLkNg0PzPw',
    appId: '1:784311936959:ios:e1d35ba7e3b3829295e30a',
    messagingSenderId: '784311936959',
    projectId: 'gayau-e5a6f',
    storageBucket: 'gayau-e5a6f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIOjUzV_wFp48zqesDq4oLTMEY3uSGhSw',
    appId: '1:784311936959:web:e0744a17f91b112595e30a',
    messagingSenderId: '784311936959',
    projectId: 'gayau-e5a6f',
    authDomain: 'gayau-e5a6f.firebaseapp.com',
    storageBucket: 'gayau-e5a6f.firebasestorage.app',
    measurementId: 'G-Y52EHRV3T5',
  );
}
